# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STEW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STEW

  pod 'NMapsMap'
  target 'STEWTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'STEWUITests' do
    # Pods for testing
  end

end
